version: '3'

services:

  php:
    build: ./
    volumes:
      - './:/app'

  database:
    volumes:
      - './data/mysql:/var/lib/mysql'
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
